version: '3'
services:
  db:
    image: mysql:5.7
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    depends_on:
      - db
      - chrome
  chrome:
    image: selenium/standalone-chrome:3.13.1-dubnium
    ports:
      - 4444:4444
volumes:
  mysql_data: