version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Settings[:db][:password]
      MYSQL_DATABASE: root
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  web:
    build: .
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    links:
      - db
volumes:
  mysql_data:
  bundle:
  