version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Sita2ra#
      MYSQL_DATABASE: root
    ports:
      - '3306:3306'
  web:
    build: .
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app_name
    links:
      - db
volumes:
  bundle:
  mysql_data: